name: Update Chrome Web Store Analytics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Chrome Web Store Data
        run: |
          curl -s "https://chrome-stats.com/api/extension/bncbklpmnbgbpnfdgkbahglbjmkcpmjd" | jq '{name: .name, version: .version, users: .users, rating: .rating, ratings_count: .ratings_count}' > chrome-analytics.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add chrome-analytics.json
          git commit -m "Update Chrome Web Store Analytics" || echo "No changes to commit"
          git push